services:
  flask-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-server
    env_file:
      - .env
    environment:
      - FLASK_ENV={FLASK_ENV}
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - template-network

networks:
  template-network:
    driver: bridge
